name: Test
on: push

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        node-version:
          - 20
          - 22
          - 24
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install apt packages
        run: |
          sudo apt-get update
          sudo apt-get install libsecret-1-dev gnome-keyring dbus-x11
      - name: Install dependencies
        run: yarn
      - name: Run test
        run: |
          eval $(dbus-launch --sh-syntax)
          eval $(echo '' | /usr/bin/gnome-keyring-daemon --unlock)
          yarn test
      - name: Send coverage to codecov
        uses: codecov/codecov-action@18283e04ce6e62d37312384ff67231eb8fd56d24 # v5.4.3
        with:
          fail_ci_if_error: true
          token: ${{ secrets.CODECOV_TOKEN }}
