name: Test
on: push

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install libsecret
        run: |
          sudo apt-get update
          sudo apt-get install libsecret-1-0 gnome-keyring
      - name: Install dependencies
        run: yarn
      - name: Run test
        run: yarn test
      - name: Send coverage to codecov
        uses: codecov/codecov-action@v5
        with:
          fail_ci_if_error: true
          token: ${{ secrets.CODECOV_TOKEN }}
